language: java

notifications:
  email:
    recipients:
      - jlee@antwerkz.com
    on_success: change
    on_failure: always

os:
  - linux
  - osx
#  - windows

jdk:
  - openjdk11

script: mvn test