name: Build

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * *'

jobs:
#  Build:
#    strategy:
#      matrix:
#        os: [ ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest ]
#        java: [ 11, 17 ]
#    uses: evanchooly/workflows/.github/workflows/build-project.yml@master
#    with:
#      os: ${{matrix.os}}
#      java: ${{matrix.java}}
  Snapshots:
#    needs:
#      - Build
    uses: evanchooly/workflows/.github/workflows/snapshots.yml@master
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
