name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  Build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest ]
        java: [ 11, 17 ]
        include:
          - java: [ 20, 21 ]
            experimental: true
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      os: ${{matrix.os}}
      java: ${{matrix.java}}
      experimental: ${{ matrix.experimental }}
  Snapshots:
    needs:
      - Build
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GH_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
