name: Experimental Builds

on: push

jobs:
  Build:
    strategy:
      matrix:
        java: [ 17 ]
        include:
          - java: [ 20, 21 ]
            experimental: true
    runs-on: ubuntu-latests
    continue-on-error: ${{ matrix.experimental == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: central

      - name: Build
        run: mvn -U install ${{ matrix.maven-flags }}



