name: Release

on:
  push:
    tags:
      - r[0-9]*

jobs:
  release:
    name: Release
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    with:
      MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}