name: Release

on:
  push:
    tags:
      - r[0-9]*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


#      - name: Release
#        env:
#          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#        run: |
#          export GPG_TTY=$(tty)
#          ./mvnw --no-transfer-progress -B --file pom.xml -Dmaven.site.skip=true -Drelease=true deploy